### ISSUE TITLE
[browser plugin] Invalid configuration format

### ISSUE THREAD

**Issue by aerogus** [coldsource/evqueue-frontend-react#2]
I have configured an evqueue-core 3.1. The server is running well on port 5000, a node on port 5001, and the react frontend is served behind an nginx in https on port 443.

In the nginx vhost I have these lines in order to route the websocket communication :

```
location /ws { # specific route to avoid conflict with the static assets
	proxy_pass http://localhost:5001; # evqueue node port
	proxy_http_version 1.1;
	proxy_set_header Upgrade $http_upgrade;
	proxy_set_header Connection 'upgrade';
	proxy_set_header Host $host;
	proxy_cache_bypass $http_upgrade;
}
```

So my `conf/cluster.json` look like :

```
{
	"local#bbbbbb": [
		"wss://evqueue.example.com/ws"
	]
}
```

The problem I have is with the browser plugin (only tested the Firefox one), the regexp of "cluster configuration" textarea in the settings page forbid me to enter my websocket url because of the route suffix "/ws"

Is that a bad way to reverse proxy websocket behind nginx, or could the regexp authorize this kind of url ?

cf . https://github.com/coldsource/evqueue-frontend-react/blob/master/htdocs/js/src/pages/settings.js#L107

Not sure it is the optimal way, but here is a proposition for the regexp :

```
^wss?:\/\/[^:]+:[0-9]+[\/[a-z]*]{0,1}$
```

**Comment by coldsource** [comment]
Hi,

Thanks for this report. I have changed configuration checks (see 8e272af03f014f098ae86c7968346b430f857bbd)

I also updated the documentation with your config sample : http://www.evqueue.net/doc/build

Regards
